# Generated by Django 4.2.4 on 2023-08-10 17:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('HN_id', models.IntegerField(null=True, unique=True)),
                ('type', models.CharField(choices=[('job', 'job'), ('story', 'story'), ('comment', 'comment'), ('poll', 'poll'), ('pollopt', 'pollopt')], max_length=10)),
                ('by', models.CharField(max_length=255, null=True)),
                ('time', models.DateTimeField(null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('dead', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quickcheck.base')),
                ('text', models.TextField(null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('url', models.URLField(null=True)),
            ],
            bases=('quickcheck.base',),
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quickcheck.base')),
                ('descendants', models.IntegerField(null=True)),
                ('score', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('text', models.TextField(null=True)),
            ],
            bases=('quickcheck.base',),
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quickcheck.base')),
                ('descendants', models.IntegerField(null=True)),
                ('score', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('url', models.URLField(null=True)),
            ],
            bases=('quickcheck.base',),
        ),
        migrations.CreateModel(
            name='PollOpt',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quickcheck.base')),
                ('score', models.IntegerField(null=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='quickcheck.poll')),
            ],
            bases=('quickcheck.base',),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quickcheck.base')),
                ('text', models.TextField(null=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kids', to='quickcheck.base')),
            ],
            bases=('quickcheck.base',),
        ),
    ]
