# Generated by Django 3.2 on 2023-08-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickcheck', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='url',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='url',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
